server:
  port: 8094

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8090/eureka/

spring:
  application:
    name: gateway

zuul:
  routes:
    hello:
      path: /hello/**
      url: http://localhost:8092/