server:
  port: 8051

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8050/eureka/

spring:
  application:
    name: gateway
  boot:
    admin:
      url: http://localhost:8060

zuul:
  routes:
    admin:
      path: /hello/**
      serviceId: admin