server:
  port: 9001

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8050/eureka/

spring:
  application:
    name: feign-consumer