server:
  port: 9002

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8050/eureka/

spring:
  application:
    name: hello-service

