server:
  port: 8091

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8090/eureka/

spring:
  application:
    name: hello-service
