spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      connection-timeout: 60000
      minimum-idle: 5
  application:
      name: admin
  boot:
    admin:
      url: http://localhost:8060
  profiles:
    include: db

logging:
  level: trace
#  config: classpath:logback-spring.xml

mybatis:
    mapper-locations: classpath:mapper/*/*/*.xml

mapper:
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql, pageSizeZero=true, reasonable=true, supportMethodsArguments=true

server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8050/eureka/
feign:
  hystrix:
    enabled: true
