server:
  port: 8050

spring:
  application:
      name: monitor-server
  boot:
    admin:
      url: http://localhost:8050


eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8090/eureka/